# **SISTEM PERSAMAAN LINIER**

**Vektor dan Ukurannya**

In [ ]:
import numpy as np
vector_row = np.array([[1, -5, 3, 2, 4]])
vector_column = np.array([[1],[2],[3],[4]])
print(vector_row.shape)
print(vector_column.shape)

(1, 5)
(4, 1)


**Transpose dan Norm Vektor**

a. Transpose digunakan untuk mengubah vektor baris menjadi vektor kolom dan sebaliknya

b. Norm vektor digunakan untuk menghitung panjang vektor


In [ ]:
from numpy.linalg import norm
new_vector = vector_row.T
print(new_vector)
norm_1 = norm(new_vector, 1)
norm_2 = norm(new_vector, 2)
norm_inf = norm(new_vector, np.inf)
print("L_1 is: %.1f"%norm_1)
print("L_2 is: %.1f"%norm_2)
print("L_inf is: %.1f"%norm_inf)

[[ 1]
 [-5]
 [ 3]
 [ 2]
 [ 4]]
L_1 is: 15.0
L_2 is: 7.4
L_inf is: 5.0


**Dot Produk dan Cross Produk**


In [ ]:
v = np.array([[10, 9, 3]])
w = np.array([[2, 5, 12]])
theta = np.arccos(np.dot(v, w.T)/(norm(v)*norm(w)))
print(theta)
v = np.array([[0, 2, 0]])
w = np.array([[3, 0, 0]])
print(np.cross(v, w))


[[0.97992471]]
[[ 0  0 -6]]


**Kombinasi Linier**

In [ ]:
v = np.array([[0, 3, 2]])
w = np.array([[4, 1, 1]])
u = np.array([[0, -2, 0]])
x =3*v-2*w+4*u
print(x)


[[-8 -1  4]]


**Matriks**

In [ ]:
P = np.array([[1, 7], [2, 3], [5, 0]])
Q = np.array([[2, 6, 3, 1], [1, 2, 3, 4]])
print("Matriks P")
print(P)
print("Matriks Q")
print(Q)
print("Matriks PxQ")
print(np.dot(P, Q))
np.dot(Q, P)

Matriks P
[[1 7]
 [2 3]
 [5 0]]
Matriks Q
[[2 6 3 1]
 [1 2 3 4]]
Matriks PxQ
[[ 9 20 24 29]
 [ 7 18 15 14]
 [10 30 15  5]]


ValueError: ignored

**Matriks Identitas, Determinan, dan Invers**

In [ ]:
from numpy.linalg import det
M = np.array([[0,2,1,3],
[3,2,8,1],
[1,0,0,3],
[0,3,2,1]])
print("M:\n",M)
print("Determinant: %.1f"%det(M))
I = np.eye(4)
print("I:\n",I)
print("M*I:\n",np.dot(M, I))
from numpy.linalg import inv
print("Inv M:\n", inv(M))
P = np.array([[0,1,0],
  [0,0,0],
  [1,0,1]])
print("det(p):", det(P))

M:
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]
Determinant: -38.0
I:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
M*I:
 [[0. 2. 1. 3.]
 [3. 2. 8. 1.]
 [1. 0. 0. 3.]
 [0. 3. 2. 1.]]
Inv M:
 [[-1.57894737 -0.07894737  1.23684211  1.10526316]
 [-0.63157895 -0.13157895  0.39473684  0.84210526]
 [ 0.68421053  0.18421053 -0.55263158 -0.57894737]
 [ 0.52631579  0.02631579 -0.07894737 -0.36842105]]
det(p): 0.0


**Perkalian Matriks LU**

In [ ]:
import numpy as np
u = np.array([[4, 3, -5],
 [0, -2.5, 2.5],
 [0, 0, 12]])
l = np.array([[1, 0, 0],
 [-0.5, 1, 0],
 [2, -0.8, 1]])
print("LU=",np.dot(l, u))

LU= [[ 4.  3. -5.]
 [-2. -4.  5.]
 [ 8.  8.  0.]]


**SPL Matriks Segitiga Atas**

In [ ]:
import numpy as np
A = [[-2, 7, -4], [0, 6, 5], [0, 0, 3]]
b = [[14],[5],[-8]]
print(A[1][2])


5


**Metode Gauss**

In [2]:
import numpy as np
import sys
 
n = int(input('Input jumlah variabel: '))
a = np.zeros((n,n+1))
x = np.zeros(n)
print('Input koefisien dan nilai kanan pada SPL:')
for i in range(n):
    for j in range(n+1):
        a[i][j] = float(input( 'a['+str(i)+']['+ str(j)+']='))
for i in range(n):
    if a[i][i] == 0.0:
        sys.exit('Terdapat nilai 0 pada diagonal utama')
         
    for j in range(i+1, n):
        ratio = a[j][i]/a[i][i]
         
        for k in range(n+1):
            a[j][k] = a[j][k] - ratio * a[i][k]
 
x[n-1] = a[n-1][n]/a[n-1][n-1]
 
for i in range(n-2,-1,-1):
    x[i] = a[i][n]
     
    for j in range(i+1,n):
        x[i] = x[i] - a[i][j]*x[j]
     
    x[i] = x[i]/a[i][i]
 
print('\nSolusi SPL adalah: ')
for i in range(n):
    print('X%d = %0.2f' %(i,x[i]), end = '\t')


Enter number of unknowns: 2
Enter Augmented Matrix Coefficients:
a[0][0]=1
a[0][1]=2
a[0][2]=2
a[1][0]=2
a[1][1]=3
a[1][2]=5

The solution is: 
X0 = 4.00	X1 = -1.00	

**Metode Gauss Jordan**

In [3]:
import numpy as np
import sys

n = int(input('Input jumlah variabel: '))
a = np.zeros((n,n+1))
x = np.zeros(n)
print('Input koefisien dan nilai kanan pada SPL:')
for i in range(n):
    for j in range(n+1):
        a[i][j] = float(input( 'a['+str(i)+']['+ str(j)+']='))

for i in range(n):
    if a[i][i] == 0.0:
        sys.exit('Terdapat nilai 0 pada diagonal utama')
        
    for j in range(n):
        if i != j:
            ratio = a[j][i]/a[i][i]

            for k in range(n+1):
                a[j][k] = a[j][k] - ratio * a[i][k]

for i in range(n):
    x[i] = a[i][n]/a[i][i]

print('\nSolusi SPL adalah: ')
for i in range(n):
    print('X%d = %0.2f' %(i,x[i]), end = '\t')

Input jumlah variabel: 2
Input koefisien dan nilai kanan pada SPL:
a[0][0]=1
a[0][1]=2
a[0][2]=2
a[1][0]=2
a[1][1]=3
a[1][2]=5

Solusi SPL adalah: 
X0 = 4.00	X1 = -1.00	

**Metode Invers**

In [28]:
# Importing NumPy Library
import numpy as np
import sys

# Reading order of matrix
n = int(input('Enter order of matrix: '))

# Making numpy array of n x 2n size and initializing 
# to zero for storing augmented matrix
a = np.zeros((n,2*n))

# Reading matrix coefficients
print('Enter Matrix Coefficients:')
for i in range(n):
    for j in range(n):
        a[i][j] = float(input( 'a['+str(i)+']['+ str(j)+']='))

# Augmenting Identity Matrix of Order n
for i in range(n):        
    for j in range(n):
        if i == j:
            a[i][j+n] = 1

# Applying Guass Jordan Elimination
for i in range(n):
    if a[i][i] == 0.0:
        sys.exit('Divide by zero detected!')
        
    for j in range(n):
        if i != j:
            ratio = a[j][i]/a[i][i]

            for k in range(2*n):
                a[j][k] = a[j][k] - ratio * a[i][k]

# Row operation to make principal diagonal element to 1
for i in range(n):
    divisor = a[i][i]
    for j in range(2*n):
        a[i][j] = a[i][j]/divisor

# Displaying Inverse Matrix
print('\nINVERSE MATRIX IS:')
for i in range(n):
    for j in range(n, 2*n):
        print(a[i][j], end='\t')
    print()

Enter order of matrix: 2
Enter Matrix Coefficients:
a[0][0]=1
a[0][1]=0
a[1][0]=1
a[1][1]=0


SystemExit: ignored

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3334: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


**Dekomposisi LU**

In [12]:
import numpy as np
import scipy.linalg
A = np.array([[1, 2, 3],
             [4, 5, 6],
             [10, 11, 9]])
P, L, U = scipy.linalg.lu(A)
print(P)
print(L)
print(U)
mult = P.dot((L.dot(U)))
print(mult)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.1        1.         0.        ]
 [0.4        0.66666667 1.        ]]
[[10.  11.   9. ]
 [ 0.   0.9  2.1]
 [ 0.   0.   1. ]]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [10. 11.  9.]]


In [ ]:
import pprint

def mult_matrix(M, N):
    """Multiply square matrices of same dimension M and N"""

    # Converts N into a list of tuples of columns                                                                                                                                                                                                      
    tuple_N = zip(*N)

    # Nested list comprehension to calculate matrix multiplication                                                                                                                                                                                     
    return [[sum(el_m * el_n for el_m, el_n in zip(row_m, col_n)) for col_n in tuple_N] for row_m in M]

def pivot_matrix(M):
    """Returns the pivoting matrix for M, used in Doolittle's method."""
    m = len(M)

    # Create an identity matrix, with floating point values                                                                                                                                                                                            
    id_mat = [[float(i ==j) for i in range(m)] for j in range(m)]

    # Rearrange the identity matrix such that the largest element of                                                                                                                                                                                   
    # each column of M is placed on the diagonal of of M                                                                                                                                                                                               
    for j in range(m):
        row = max(range(j, m), key=lambda i: abs(M[i][j]))
        if j != row:
            # Swap the rows                                                                                                                                                                                                                            
            id_mat[j], id_mat[row] = id_mat[row], id_mat[j]

    return id_mat

def lu_decomposition(A):
    """Performs an LU Decomposition of A (which must be square)                                                                                                                                                                                        
    into PA = LU. The function returns P, L and U."""
    n = len(A)

    # Create zero matrices for L and U                                                                                                                                                                                                                 
    L = [[0.0] * n for i in range(n)]
    U = [[0.0] * n for i in range(n)]

    # Create the pivot matrix P and the multipled matrix PA                                                                                                                                                                                            
    P = pivot_matrix(A)
    PA = mult_matrix(P, A)

    # Perform the LU Decomposition                                                                                                                                                                                                                     
    for j in range(n):
        # All diagonal entries of L are set to unity                                                                                                                                                                                                   
        L[j][j] = 1.0

        # LaTeX: u_{ij} = a_{ij} - \sum_{k=1}^{i-1} u_{kj} l_{ik}                                                                                                                                                                                      
        for i in range(j+1):
            s1 = sum(U[k][j] * L[i][k] for k in range(i))
            U[i][j] = PA[i][j] - s1

        # LaTeX: l_{ij} = \frac{1}{u_{jj}} (a_{ij} - \sum_{k=1}^{j-1} u_{kj} l_{ik} )                                                                                                                                                                  
        for i in range(j,n):
            s2 = sum(U[k][j] * L[i][k] for k in range(j))
            L[i][j] = (PA[i][j] - s2) / U[j][j]

    return (P, L, U)


A = [[7, 3, -1, 2], [3, 8, 1, -4], [-1, 1, 4, -1], [2, -4, -1, 6]]
P, L, U = lu_decomposition(A)

print("A:")
pprint.pprint(A)

print("P:")
pprint.pprint(P)

print("L:")
pprint.pprint(L)

print("U:")
pprint.pprint(U)

**Iterasi Jacobi**

In [27]:
from pprint import pprint
from numpy import array, zeros, diag, diagflat, dot

def jacobi(A,b,N=25,x=None):
    """Solves the equation Ax=b via the Jacobi iterative method."""
    # Create an initial guess if needed                                                                                                                                                            
    if x is None:
        x = zeros(len(A[0]))

    # Create a vector of the diagonal elements of A                                                                                                                                                
    # and subtract them from A                                                                                                                                                                     
    D = diag(A)
    R = A - diagflat(D)

    # Iterate for N times                                                                                                                                                                          
    for i in range(N):
        x = (b - dot(R,x)) / D
    return x

A = array([[2.0,1.0],[5.0,7.0]])
b = array([11.0,13.0])
guess = array([1.0,1.0])

sol = jacobi(A,b,N=25,x=guess)

print ("A:")
pprint(A)

print ("b:")
pprint(b)

print ("x:")
pprint(sol)

A:
array([[2., 1.],
       [5., 7.]])
b:
array([11., 13.])
x:
array([ 7.11110202, -3.22220342])


**Metode Gauss Siedel**

In [ ]:
import numpy as np
a = [[8, 3, -3], [-2, -8, 5], [3, 5, 10]]
# Find diagonal coefficients
diag = np.diag(np.abs(a))
# Find row sum without diagonal
off_diag = np.sum(np.abs(a), axis=1) - diag
if np.all(diag > off_diag):
  print("matrix is diagonally dominant")
else:
  print("NOT diagonally dominant")

x1 =0
x2 =0
x3 =0
epsilon = 0.01
converged = False
x_old = np.array([x1, x2, x3])
print("Iteration results")
print(" k, x1, x2, x3 ")
for k in range(1, 50):
  x1 = (14-3*x2+3*x3)/8 
  x2 = (5+2*x1-5*x3)/(-8)
  x3 = (-8-3*x1-5*x2)/(10)
  x = np.array([x1, x2, x3])
  # check if it is smaller than threshold
  dx = np.sqrt(np.dot(x-x_old, x-x_old))
  
  print("%d, %.4f, %.4f, %.4f"%(k, x1, x2, x3))
  if dx< epsilon:
    converged = True
    print("Converged!")
    break
  
  # assign the latest x value to the old value
    x_old = x

if not converged:
  print("Not converged, increase the number of iterations")

matrix is diagonally dominant
Iteration results
 k, x1, x2, x3 
1, 1.7500, -1.0625, -0.7937
2, 1.8508, -1.5838, -0.5633
3, 2.1327, -1.5103, -0.6847
4, 2.0596, -1.5678, -0.6340
5, 2.1002, -1.5463, -0.6569
6, 2.0835, -1.5565, -0.6468
7, 2.0911, -1.5520, -0.6513
8, 2.0878, -1.5540, -0.6493
9, 2.0893, -1.5531, -0.6502
10, 2.0886, -1.5535, -0.6498
11, 2.0889, -1.5534, -0.6500
12, 2.0888, -1.5534, -0.6499
13, 2.0888, -1.5534, -0.6499
14, 2.0888, -1.5534, -0.6499
15, 2.0888, -1.5534, -0.6499
16, 2.0888, -1.5534, -0.6499
17, 2.0888, -1.5534, -0.6499
18, 2.0888, -1.5534, -0.6499
19, 2.0888, -1.5534, -0.6499
20, 2.0888, -1.5534, -0.6499
21, 2.0888, -1.5534, -0.6499
22, 2.0888, -1.5534, -0.6499
23, 2.0888, -1.5534, -0.6499
24, 2.0888, -1.5534, -0.6499
25, 2.0888, -1.5534, -0.6499
26, 2.0888, -1.5534, -0.6499
27, 2.0888, -1.5534, -0.6499
28, 2.0888, -1.5534, -0.6499
29, 2.0888, -1.5534, -0.6499
30, 2.0888, -1.5534, -0.6499
31, 2.0888, -1.5534, -0.6499
32, 2.0888, -1.5534, -0.6499
33, 2.0888, -1.55

In [29]:
# Gauss Seidel Iteration

# Defining equations to be solved
# in diagonally dominant form
f1 = lambda x,y,z: (17-y+2*z)/20
f2 = lambda x,y,z: (-18-3*x+z)/20
f3 = lambda x,y,z: (25-2*x+3*y)/20

# Initial setup
x0 = 0
y0 = 0
z0 = 0
count = 1

# Reading tolerable error
e = float(input('Enter tolerable error: '))

# Implementation of Gauss Seidel Iteration
print('\nCount\tx\ty\tz\n')

condition = True

while condition:
    x1 = f1(x0,y0,z0)
    y1 = f2(x1,y0,z0)
    z1 = f3(x1,y1,z0)
    print('%d\t%0.4f\t%0.4f\t%0.4f\n' %(count, x1,y1,z1))
    e1 = abs(x0-x1);
    e2 = abs(y0-y1);
    e3 = abs(z0-z1);
    
    count += 1
    x0 = x1
    y0 = y1
    z0 = z1
    
    condition = e1>e and e2>e and e3>e

print('\nSolution: x=%0.3f, y=%0.3f and z = %0.3f\n'% (x1,y1,z1))

Enter tolerable error: 0.1

Count	x	y	z

1	0.8500	-1.0275	1.0109

2	1.0025	-0.9998	0.9998


Solution: x=1.002, y=-1.000 and z = 1.000

